#include "shared_lib.h"

// msg_get() -> returns msgqid
int message_get(){
    int msgqid = msgget(QUEUE_KEY, QUEUE_PERMISSION);

    if(msgqid == -1){
        perror("msgget failure\n");
        exit(EXIT_FAILURE);
    }
    return msgqid;
}

// msg_snd() -> -1 or 0
void message_send(struct msg_data* data, char* request){
    int msgqid = message_get();
    char temp_data[BUFFER_SIZE];

    sprintf(data->message, request); // this is the request message being sent to the server

    data->client_pid = getpid(); // server will use this to write back

    if(msgsnd(msgqid, (void*) data, sizeof(*data), 0) == -1){
        perror("msgsnd failed\n");
        exit(EXIT_FAILURE);
    }
}

// msg_rcv() -> # bytes received or -1
key_t message_receive(struct msg_data *data){
    int msgqid = message_get();

    if(msgrcv(msgqid, (void*) data, sizeof(*data), data->msg_type, 0) == -1){
        perror("msgrcv failed\n");
        exit(EXIT_FAILURE);
    }

    int key; // response sent from server
    sscanf(data->message, "RESPONSE;%d", &key);
    return (key_t) key;
}

// return the shared memory key generated by server
key_t get_shm_key(struct msg_data* data, char* request){
    data->msg_type = SERVER_MSG_TYPE; // send a type 1 for server to read
    sprintf(request, "REQUEST;%s", SH_MEM_REQ_MSG);
    message_send(data, request);

    // shared memory key received from server
    data->msg_type = getpid(); // receive to client that sent the request
    return message_receive(data);
}

// return the semaphore key generated by server
key_t get_sem_key(struct msg_data* data, char* request){
    data->msg_type = SERVER_MSG_TYPE; // send a type 1 for server to read
    sprintf(request, "REQUEST;%s", SEM_REQ_MSG);
    message_send(data, request);

    // semaphore key received from server
    data->msg_type = getpid(); // receive to client that sent the request
    return message_receive(data);
}

// get shared memory region
key_t get_shared_mem(key_t *shm_key){
    key_t shmid = shmget(*shm_key, sizeof(struct shm_buffer) * NUM_BUFFER, SHM_PERMISSION);
    if (shmid == -1){
        fprintf(stderr, "shmget failed\n");
        exit(EXIT_FAILURE);
    }
    return shmid;
}
// attach to the shared memory region
void attach_shared_mem(key_t* shmid, void* shm_ptr){
    printf("shmid: %d\n", *shmid);
    shm_ptr = shmat(*shmid, (void *)0, 0);
    if (shm_ptr == (void *)-1){
        fprintf(stderr, "shmat failed\n");
        exit(EXIT_FAILURE);
    }
}

int main(){

    int msgqid; // queue message id
    struct msg_data data; // queue data struct
    key_t shm_key, sem_key; // resource keys generated by server
    char request[BUFFER_SIZE]; // what type of request am i making, ex. 'sh_key'
    key_t shmid; // shared memory region id

    // the shared memory buffer pointer; attach this
    struct shm_buffer* shared_memory;
    void *shm_ptr = (void *) 0; // point to the shared region

    msgqid = message_get();

    /* REQUEST SHARED MEMORY KEY */
    shm_key = get_shm_key(&data, &request);
    attach_shared_mem(&shmid, shm_ptr);
    shared_memory = (struct shm_buffer *) shm_ptr;

    printf("Shared Memory Key: %d\n", shm_key);
    printf("Shared Memory ID: %d\n", shmid);
    printf("Shared Memory Address: %X\n", (int) shm_ptr);


    /* REQUEST SEMAPHORE KEY */
    sem_key = get_sem_key(&data, &request);
    printf("Semaphore Key: %d\n", sem_key);

    return 0;
}